id: testkorpus
name: Testkorpus

# Elements and attributes from the source XML that we want to be available as input for other annotations
xml_elements:
  - text:date

sentence_chunk: <text>

dateformat.date_from: <text>:date
dateformat.date_to: <text>:date
dateformat.informat: "%Y-%m-%d"

annotations:
  - text
  - <text>:readability.lix
  - <sentence>
  - <token>
  - <token:pos>
  - <token>:misc.number_rel_<sentence> as ref

original_annotations:
  - dokument as document
  - text:id
  - text:date
  - text:forfattare as author

classes:
    token: segment.token
    text: text
